[build]
  # مجلد النشر
  publish = "public"
  # أمر البناء (إذا كان لديك عملية بناء)
  command = "echo 'Building static site...'"

[build.environment]
  # متغيرات البيئة
  NODE_VERSION = "18"

# إعدادات Functions
[functions]
  # مجلد الـ Functions
  directory = "netlify/functions"

# إعدادات إعادة التوجيه والقواعد
[[redirects]]
  # إعادة توجيه API للطلبات
  from = "/api/orders/*"
  to = "/.netlify/functions/admin-dashboard/:splat"
  status = 200

[[redirects]]
  # إعادة توجيه API لتتبع المراسلين
  from = "/api/tracking/*"
  to = "/.netlify/functions/real-time-tracking/:splat"
  status = 200

[[redirects]]
  # إعادة توجيه API للإحصائيات
  from = "/api/stats/*"
  to = "/.netlify/functions/admin-dashboard/:splat"
  status = 200

[[redirects]]
  # إعادة توجيه API للمراسلين
  from = "/api/messengers/*"
  to = "/.netlify/functions/admin-dashboard/:splat"
  status = 200

[[redirects]]
  # الصفحة الرئيسية
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  # لوحة الإدارة
  from = "/admin"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  # تتبع المراسلين
  from = "/tracking"
  to = "/messenger-tracking.html"
  status = 200

[[redirects]]
  # معالجة المسارات غير الموجودة (SPA fallback)
  from = "/*"
  to = "/index.html"
  status = 404

# إعدادات Headers للأمان والأداء
[[headers]]
  for = "/*"
  [headers.values]
    # CORS Headers
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache Control
    Cache-Control = "public, max-age=31536000"

# إعدادات خاصة للملفات الديناميكية
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# إعدادات متقدمة للـ Functions
[context.production.environment]
  NODE_ENV = "production"
  API_URL = "https://your-site.netlify.app"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  API_URL = "https://deploy-preview-123--your-site.netlify.app"

[context.branch-deploy.environment]
  NODE_ENV = "staging"
  API_URL = "https://branch-name--your-site.netlify.app"
